#Skills

skills:
- {name: Communication, value: '9'}
- {name: Organization, value: '7'}
- {name: Learning, value: '10'}
- {name: Version Control, value: '6'}
- {name: Planning, value: '7'}
- {name: Visual Design, value: '5'}
- {name: UX Design, value: '8'}
- {name: Programming, value: '6'}

clients:
- {name: 'Maxima', about: "<p><strong>In pellentesque faucibus vestibulum.</strong> Nulla at nulla justo, eget luctus tortor. Nulla facilisi. Duis aliquet egestas purus in blandit. Curabitur vulputate, ligula lacinia scelerisque tempor, lacus lacus ornare ante, ac egestas est urna sit amet arcu. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed molestie augue sit amet leo.</p>", logo: 'clients2.png'}
- {name: 'Salmo', about: "<p><strong>Things get better</strong> when you're high. Cocaine, however, is one hell of a drug.</p>", logo: 'clients4.png'}
- {name: 'Einberg', about: "<p><strong>Is this what I desired it to be</strong>, or is this slumber that will follow? I expect more to come of this.</p>", logo: 'clients3.png'}
- {name: 'Kavial', about: "<p><strong>This is a bigger and better part of me that I don't understand</strong>,and that I cannot control for the life of me. The response is vague. Who said what now?</p>", logo: 'clients1.png'}
